### ISSUE TITLE
Todo Next Version

### ISSUE THREAD

**Issue by Thecarisma** [barmoury/barmoury-ts#4]
- [ ] add ValidationQuery for ts
- [ ] add ValidateFields for ts
- [ ] add ValidationRequest for both JVM and ts
- [ ] change none to (null) for unset fields in the validation
- [ ] support for sub-entity in resource fetch
